### PR TITLE
Venues Padding ,External Links and some small changes.

### PR DESCRIPTION
**Pull request by arwinneil**
- Added link to "VIEW ON YOUTUBE" button in index.html

- Added missing padding in right side containers in venue.html
Preview

- Added [Meetup event link for Global Azure Bootcamp 2016](https://www.meetup.com/MauritiusSoftwareCraftsmanshipCommunity/events/226532196/)  , Past Event Section in index.html

- Updated favicon to a multisize (16x16,32x32,48x48) .ico file, for better look on some mobile web browsers.

screenshot_2017-01-24-00-19-42 01
(larger favicon preview as used by Chrome on Android)

-  Added favicon to index.html and venue.html

p3

### CODE REVIEW

**Comment by Humeira** [comment]
@nirvanpagooah As we spoke on Slack, you have already fixed the padding on `venue.html`, it's in your next iteration.

However can you check this PR?

**Comment by Humeira** [comment]
@arwinneil Conflicts, please correct.

**Comment by arwinneil** [comment]
@Humeira Resolved conflicts, thanks.

**Comment by jochenkirstaetter** [comment]
Thanks Arwin, don't forget to add yourself to the humans.txt

**Comment by arwinneil** [comment]
Hello @jochenkirstaetter ,
I apologise in advance starting a conversation here, but that's the best I could think of.

Meant to ask; found some issues and unfortunately I'm unable to fix it. **Is it fine opening issues on this repository** or is there another way of communicating issues to other members of the team?

Thanks,
@arwinneil

**Pull request merged**
